logging:
  level:
    io.github.cepr0: debug
    org.springframework:
      orm: debug
      security: debug
      web: debug
      amqp: debug

demo:
  queue: demo.queue

server:
  port: 8091


management:
  server:
    port: 8092
    servlet:
      context-path: /server