server:
  forward-headers-strategy: framework
  shutdown: graceful

spring:
  application:
    name: response-service
  main:
    banner-mode: off
  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true

