POST http://{{request-service}}/demo
Content-Type: application/json

{
  "client": 1,
  "request": "hello"
}

###

POST http://{{request-service}}/models
Content-Type: application/json

{
  "num": {{$randomInt}},
  "text": "{{$uuid}}"
}

###

GET http://{{request-service}}/models

###

GET http://{{request-service}}/actuator/health

###