logging:
  level:
    io.github.cepr0: debug
    org.springframework:
      security: debug
      web: debug
      amqp: debug

server:
  port: 8081


management:
  server:
    port: 8082
    servlet:
      context-path: /client