server:
  forward-headers-strategy: framework
  shutdown: graceful
  error:
    include-message: always

spring:
  application:
    name: request-service
  main:
    banner-mode: off
  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  jackson:
    time-zone: UTC
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null
    serialization:
      write_dates_as_timestamps: true
      write_date_timestamps_as_nanoseconds: false
      fail_on_empty_beans: false



